cursor #e2e2e2
cursor_text_color #c6c6c6

foreground            #e2e2e2
background            #131313
selection_foreground  #442a23
selection_background  #e7bdb3
url_color             #ffb4a3

color0   #131313
color1   #ff7572
color2   #98ff7f
color3   #ffe472
color4   #f29c89
color5   #763627
color6   #ffb4a3
color7   #fff2ef
color8   #a59b99
color9   #ffa19f
color10  #b7ffa5
color11  #ffeea5
color12  #ffbfb0
color13  #ffcabe
color14  #ffddd5
color15  #fff9f8
