# settings.toml is noctalia owned. It resides in ~/.local/state/noctalia/settings.toml
# config.toml is user owned it resides in ~/.config/noctalia/*.toml
# How to make custom widgets: https://docs.noctalia.dev/v5/bar/widgets/

[widget.swap]
type = "sysmon"
stat = "swap_pct"
glyph = "memory"

[widget.disk]
type = "sysmon"
stat = "disk_used_pct"
glyph = "storage"

[widget.textdot]
type = "text"
text = "•"
interactive = false

[widget.textspace]
type = "text"
text = " "
interactive = false

# Hide network/wifi applet and bluemand from sys tray as there are already dedicated widgets for them
[widget.tray]
hidden = ["blueman", "network"]
