config_version = 14

[bar]
order = [ "default" ]

    [bar.default]
    capsule = true
    capsule_padding = 8.0
    capsule_radius = 8
    capsule_thickness = 0.59999999031424522
    center = [ "cpu", "temp", "ram", "swap", "control-center", "disk", "battery", "network_rx", "network_tx", "widget" ]
    end = [ "group:g3", "tray", "group:g1", "group:g4", "session" ]
    font_family = "IBM Plex Sans Text"
    margin_ends = 0
    padding = 8
    radius = 0
    radius_bottom_left = 12
    radius_bottom_right = 12
    scale = 0.90000000596046448
    shadow = false
    start = [ "launcher", "group:g5", "weather", "privacy", "toggle", "workspaces" ]
    thickness = 38

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g4"
        members = [
            "status",
            "textspace",
            "brightness",
            "textspace",
            "input_volume",
            "textspace",
            "volume",
            "textspace",
            "bluetooth",
            "textspace",
            "network",
            "textspace",
            "notifications"
        ]
        opacity = 1.0
        padding = 8.0
        radius = 8.0

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g3"
        members = [ "media", "audio_visualizer" ]
        opacity = 1.0
        padding = 8.0
        radius = 8.0

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g5"
        members = [ "bar_2", "clock" ]
        opacity = 1.0
        padding = 8.0
        radius = 8.0

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "widget_2", "textspace", "notes", "textspace", "caffeine" ]
        opacity = 1.0
        padding = 8.0
        radius = 8.0

[control_center]
sidebar = "full"

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "system"

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
background_opacity = 0.79999998211860657
cross_axis_padding = 4
enabled = true
icon_size = 32
inactive_opacity = 0.99999997764825821
main_axis_padding = 8
pinned = [
    "com.mitchellh.ghostty",
    "org.gnome.Nautilus",
    "firefox",
    "librewolf",
    "dev.zed.Zed",
    "net.nokyan.Resources",
    "steam",
    "de.haeckerfelix.Shortwave",
    "com.stremio.Stremio",
    "org.signal.Signal",
    "re.fossplant.songrec",
    "com.github.wwmm.easyeffects"
]
radius = 12
reserve_space = false
show_dots = true
smart_auto_hide = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[location]
address = "toronto, canada"

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-widget-0000000000000001", "lockscreen-widget-0000000000000002" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 336.0
    cx = 1024.0
    cy = 787.0
    output = "eDP-1"
    placement_height = 1280.0
    placement_width = 2048.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 0.0
    box_width = 0.0
    cx = 1024.0
    cy = 640.0
    output = "eDP-1"
    placement_height = 1280.0
    placement_width = 2048.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 560.0
    box_width = 640.0
    cx = 1018.0
    cy = 290.0
    output = "eDP-1"
    placement_height = 1280.0
    placement_width = 2048.0
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = false
        visualization_mode = "all"

[notification]
background_opacity = 0.9499999787658453

[plugin_settings."alexander/screen-toolkit"]
panel_open_near_click = true
panel_placement = "attached"
x02-expiry = "1h"

[plugin_settings."aristides/udiskie"]
manager_open_near_click = true
manager_placement = "attached"

[plugins]
enabled = [
    "noctalia/bongocat",
    "noctalia/notes",
    "noctalia/screen_recorder",
    "noctalia/timer",
    "noctalia/wallhaven",
    "maddingo/hypr-layout-switcher",
    "noctalia/world_clock",
    "alexander/screen-toolkit",
    "aristides/udiskie",
    "tmelik/system-monitor",
    "piero-93/battery-power-management"
]

[shell]
avatar_path = "/home/echoes/Pictures/DP/faces/cat.jpg"
font_family = "IBM Plex Sans Text"
polkit_agent = true

    [shell.panel]
    open_near_click_control_center = true
    shadow = false
    transparency_mode = "soft"

[theme]
builtin = "Noctalia"
community_palette = "Neon Surf"
custom_palette = "cogs-minimal-rb"
source = "wallpaper"
wallpaper_scheme = "m3-rainbow"

    [theme.templates]
    builtin_ids = [ "cava", "gtk3", "gtk4", "hyprland", "kcolorscheme", "mango", "niri", "qt" ]
    community_ids = [ "zed", "steam", "papirus-icons" ]

[wallpaper]
directory = "/home/echoes/Pictures"
fill_color = "#000000"
transition_on_startup = true

    [wallpaper.default]
    path = "/home/echoes/Pictures/smoothis-blue-wallhaven-og6jkp.png"

    [wallpaper.last]
    path = "/home/echoes/Pictures/smoothis-blue-wallhaven-og6jkp.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/echoes/Pictures/smoothis-blue-wallhaven-og6jkp.png"

[widget.audio_visualizer]
bands = 32
color_1 = "on_surface"
color_2 = "on_surface"
interactive = false
show_when_idle = true
width = 48

[widget.bar_2]
type = "noctalia/world_clock:bar"

[widget.brightness]
show_label = false

    [widget.brightness.actions]
    scroll_down = "brightness-down 1"
    scroll_up = "brightness-up 1"

[widget.clock]
format = "{:%H:%M}  •  {:%a}, {:%d}"

[widget.control-center]
anchor = true
color = "primary"
glyph = "badges-filled"

[widget.cpu]
visualization = "none"

[widget.disk]
visualization = "none"

[widget.input_volume]
color = "error"
mute_color = "on_surface"
show_label = false

    [widget.input_volume.actions]
    scroll_down = "mic-volume-down 1"
    scroll_up = "mic-volume-up 1"

[widget.launcher]
glyph = "menu-2"

[widget.media]
album_art_only = true
max_length = 134

[widget.network]
show_label = false

[widget.network_rx]
network_speed_compact = true
visualization = "none"

[widget.network_tx]
network_speed_compact = true
visualization = "none"

[widget.notes]
type = "noctalia/notes:notes"

[widget.privacy]
active_color = "error"
hide_inactive = true

[widget.ram]
stat = "ram_pct"
visualization = "none"

[widget.session]
enabled = false

[widget.status]
type = "aristides/udiskie:status"

[widget.swap]
visualization = "none"

[widget.temp]
visualization = "none"

[widget.toggle]
type = "maddingo/hypr-layout-switcher:toggle"

[widget.tray]
match_adjacent_spacing = true

[widget.volume]
show_label = false

    [widget.volume.actions]
    scroll_down = "volume-down 1"
    scroll_up = "volume-up 1"

[widget.weather]
show_condition = false

[widget.widget]
type = "piero-93/thinkpad-fan:widget"

[widget.widget_2]
type = "alexander/screen-toolkit:widget"

[widget.workspaces]
active_pill_size = 1.75
empty_color = "on_surface"
focused_output_only = true
occupied_color = "on_surface"
scroll_repeat = "steps"
style = "minimal"