# Noctalia Theme for Mango
# Generated automatically by Noctalia

rootcolor = 0x131313ff
bordercolor = 0x919191ff
dropcolor = 0xa9c7ff80
splitcolor = 0xdcbce1ff
focuscolor = 0xa9c7ffff
maximizescreencolor = 0xbec7dcff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xdcbce1ff
globalcolor = 0x00468cff
overlaycolor = 0x3e4759ff
jump_label_decorate_fg_color = 0xe2e2e2ff
jump_label_decorate_bg_color = 0x2a2a2aff
jump_label_decorate_focus_fg_color = 0x003064ff
jump_label_decorate_focus_bg_color = 0xa9c7ffff
jump_label_decorate_border_color = 0x919191ff
group_bar_decorate_fg_color = 0xe2e2e2ff
group_bar_decorate_bg_color = 0x2a2a2aff
group_bar_decorate_focus_fg_color = 0x003064ff
group_bar_decorate_focus_bg_color = 0xa9c7ffff
group_bar_decorate_border_color = 0x919191ff
