# ~/.tmux.conf

# ============================================
# ESSENTIAL SETTINGS
# ============================================

set-option -g default-shell "${SHELL}"
set -g mouse on
set -g set-clipboard on
bind r source-file ~/.tmux.conf \; display "Reloaded!"      # Reload config file

# ============================================
# APPEARANCE
# ============================================

set -g status-style 'bg=lightblue fg=black'
set -g pane-border-style fg='#666666'
set -g pane-active-border-style fg=lightblue
set -g pane-border-lines 'heavy'
set -g status-position bottom

set -g window-status-current-format '#S.#I.#P:#W'
set -g window-status-format '#S.#I.#P:#W'
set -g window-status-separator ' | '
set -g status-left ''
set -g status-right ''
set -g status-justify centre
set -g window-status-current-style 'bold underscore'

# ============================================
# PLUGINS (via TPM)
# ============================================

# Install TPM first:
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
set -g @plugin 'tmux-plugins/tpm'
run '~/.tmux/plugins/tpm/tpm'

